name: Composer Plugin

on: [push, pull_request]

jobs:
    composer_plugin:
        name: PHP ${{ matrix.php-versions }} with Composer ${{ matrix.composer-versions }}
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 6
            fail-fast: false
            matrix:
                php-versions:
                    - "7.3"
                    - "7.4"
                    - "8.0"
                composer-versions:
                    - "v1"
                    - "v2"
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup PHP version and composer
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: composer:${{ matrix.composer-versions }}

            - name: Environment Check
              run: |
                  php --version
                  composer --version

            - name: Require Composer@v1
              if: ${{ matrix.composer-versions == 'v1' }}
              run: composer require "composer/composer:^1.10" --dev --no-update

            - name: Require Composer@v2
              if: ${{ matrix.composer-versions == 'v2' }}
              run: composer require "composer/composer:^2.0" --dev --no-update

            - name: Install composer dependencies
              run: composer install

            - name: Info
              run: composer info

            - name: Unit Tests
              run: vendor/bin/phpunit
