# inspired at https://github.com/phpstan/extension-installer/blob/master/.github/workflows/integration-tests.yml
name: Rector Install

on: [push, pull_request]

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    rector_install:
        name: "Rector install"
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -
                run: composer install --no-interaction --no-progress
                working-directory: e2e

            # this must run without error and show 1 diff, or the rector/rector-nette config was not registered propperly
            -
                run: vendor/bin/rector
                working-directory: e2e
