# inspired at https://github.com/phpstan/extension-installer/blob/master/.github/workflows/integration-tests.yml
name: Rector Install

on: [push, pull_request]

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    rector_install:
        name: PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions:
                    - "7.3"
                    - "7.4"
                    - "8.0"

        steps:
            -
                uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -
                run: composer install --no-interaction --no-progress
                working-directory: e2e

            # this must run without error and show 1 diff, or the rector/rector-nette config was not registered propperly
            -
                run: vendor/bin/rector
                working-directory: e2e
